export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        secondary: '#63597c',
        'surface-variant': '#e6e0e9',
        'secondary-fixed': '#e9ddff',
        surface: '#fdf7ff',
        background: '#fdf7ff',
        tertiary: '#765b00',
        'primary-container': '#6750a4',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#1f1635',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#cdc0e9',
        'inverse-primary': '#cfbcff',
        'on-tertiary-fixed': '#241a00',
        'on-surface-variant': '#494551',
        'on-tertiary-container': '#503d00',
        outline: '#7a7582',
        'tertiary-fixed': '#ffdf93',
        'tertiary-container': '#c9a74d',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ded8e0',
        'on-tertiary-fixed-variant': '#594400',
        'on-primary-container': '#e0d2ff',
        'surface-container': '#f2ecf4',
        'surface-bright': '#fdf7ff',
        'primary-fixed-dim': '#cfbcff',
        'primary-fixed': '#e9ddff',
        'on-background': '#1d1b20',
        'on-error': '#ffffff',
        'surface-tint': '#6750a4',
        'secondary-container': '#e1d4fd',
        'surface-container-highest': '#e6e0e9',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#4b4263',
        'on-primary-fixed': '#22005d',
        'surface-container-high': '#ece6ee',
        'surface-container-low': '#f8f2fa',
        'on-secondary-container': '#645a7d',
        'inverse-surface': '#322f35',
        'outline-variant': '#cbc4d2',
        'inverse-on-surface': '#f5eff7',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#4f378a',
        primary: '#4f378a',
        'tertiary-fixed-dim': '#e7c365',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-page': '64px',
        unit: '4px',
        'element-gap': '24px',
        'container-max': '1440px',
        gutter: '32px',
        'section-gap': '120px',
      },
      fontFamily: {
        'display-xl': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        h2: ['Inter'],
        h1: ['Inter'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
